/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtRFilter.C
// ************************************************************************* //

#include <avtRFilter.h>
#include <avtTMP.h>
#include <avtDatasetExaminer.h>
#include <avtContract.h>
#include <avtSourceFromAVTDataset.h>
#include <vtkDataSet.h>
#include <vtkPointData.h>
#include <vtkCellData.h>
#include <vtkFloatArray.h>
#include <string.h>
#include <DebugStream.h>
#include <InstallationFunctions.h>
#include <string>
#include <InvalidFilesException.h>

// ****************************************************************************
//  Method: avtRFilter constructor
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

avtRFilter::avtRFilter()
{
    //RegisterOperation("monthlyMax", MonthlyMaxOperation);
    //RegisterOperation("exceed",Exceed
}


// ****************************************************************************
//  Method: avtRFilter destructor
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
//  Modifications:
//
// ****************************************************************************

avtRFilter::~avtRFilter()
{
}


// ****************************************************************************
//  Method:  avtRFilter::Create
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

avtFilter *
avtRFilter::Create()
{
    return new avtRFilter();
}


// ****************************************************************************
//  Method:      avtRFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

void
avtRFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const RAttributes*)a;
}


// ****************************************************************************
//  Method: avtRFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtRFilter with the given
//      parameters would result in an equivalent avtRFilter.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

bool
avtRFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(RAttributes*)a);
}


// ****************************************************************************
//  Method: avtRFilter::Execute
//
//  Purpose:
//      Sends the specified input and output through the R filter.
//
//  Arguments:
//      in_ds      The input dataset.
//      <unused>   The domain number.
//      <unused>   The label.
//
//  Returns:       The output dataset.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

void
avtRFilter::Execute()
{
    avtMonthlyIteratorOperation *f = new avtMonthlyIteratorOperation();

    //f->atts = atts;
    f->SetInput(GetInput());

    avtContract_p spec = GetInput()->GetOriginatingSource()->GetGeneralContract();
    avtDataObject_p dob = f->GetOutput();

    dob->Update(spec);
    avtDataTree_p tree = f->GetTypedOutput()->GetDataTree();

    //Set the output variable properly.
    int nleaves;
    vtkDataSet **leaves = tree->GetAllLeaves(nleaves);
    for (int i = 0; i < nleaves; i++)
    {
        if (leaves[i]->GetPointData()->GetScalars())
            leaves[i]->GetPointData()->GetScalars()->SetName(pipelineVariable);
        else if (leaves[i]->GetCellData()->GetScalars())
            leaves[i]->GetCellData()->GetScalars()->SetName(pipelineVariable);
    }
    delete [] leaves;

    SetOutputDataTree(tree);
    delete f;
}


