/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtRFilter.C
// ************************************************************************* //

#include <avtRFilter.h>
#include <avtTMP.h>
#include <avtDatasetExaminer.h>
#include <avtContract.h>
#include <avtSourceFromAVTDataset.h>
#include <vtkDataSet.h>
#include <vtkPointData.h>
#include <vtkCellData.h>
#include <vtkFloatArray.h>
#include <string.h>
#include <DebugStream.h>
#include <InstallationFunctions.h>
#include <string>
#include <InvalidFilesException.h>
#include <avtRExtremesFilter.h>
#include <avtRSimpleFilter.h>

#include <ScriptOperation.h>

// ****************************************************************************
//  Method: avtRFilter constructor
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

avtRFilter::avtRFilter()
{
    //RegisterOperation("monthlyMax", MonthlyMaxOperation);
    //RegisterOperation("exceed",Exceed
    rtimeOp.setRFilter(this);
    revOp.setRFilter(this);
    rmiOp.setRFilter(this);
    rsimpleOp.setRFilter(this);
}


// ****************************************************************************
//  Method: avtRFilter destructor
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
//  Modifications:
//
// ****************************************************************************

avtRFilter::~avtRFilter()
{
}


// ****************************************************************************
//  Method:  avtRFilter::Create
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

avtFilter *
avtRFilter::Create()
{
    return new avtRFilter();
}


// ****************************************************************************
//  Method:      avtRFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

void
avtRFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const RAttributes*)a;
}


// ****************************************************************************
//  Method: avtRFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtRFilter with the given
//      parameters would result in an equivalent avtRFilter.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

bool
avtRFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(RAttributes*)a);
}


// ****************************************************************************
//  Method: avtRFilter::Execute
//
//  Purpose:
//      Sends the specified input and output through the R filter.
//
//  Arguments:
//      in_ds      The input dataset.
//      <unused>   The domain number.
//      <unused>   The label.
//
//  Returns:       The output dataset.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Jan 15 16:19:34 PST 2013
//
// ****************************************************************************

void
avtRFilter::Execute()
{        
    avtRScriptWithArgsFilter *f1 = new avtRScriptWithArgsFilter();
    f1->argNames.push_back("val1");
    f1->arguments.push_back(1.0);
    
    f1->inputName = "inData";
    f1->outputName = "output";

    f1->rcode = "output <- inData[1] * val1";


    avtOpOverTimeFilter *f2 = new avtOpOverTimeFilter();
    f2->operation = MAX_OPERATOR;

    f2->SetInput(GetInput());
    

    /*
    avtRSimpleFilter *f = new avtRSimpleFilter();
    f->cutoff = 0.00025;
    f->percentile = 0.9;
    */

    /*
    //Do extremes..
    avtRExtremesFilter *f = new avtRExtremesFilter();
    f->codeDir = "/apps/visit/branches/VisIt/lib/r_support/Rscripts";
    */

    /*
    //avtMonthlyIteratorOperation *f = new avtMonthlyIteratorOperation();
    avtMonthlyExceedencesOperation *f = new avtMonthlyExceedencesOperation();
    f->operation = MAX_OPERATOR;
    //f->atts = atts;
    */

    avtContract_p spec = GetInput()->GetOriginatingSource()->GetGeneralContract();
    avtDataObject_p dob = f2->GetOutput();

    dob->Update(spec);
    avtDataTree_p tree = f2->GetTypedOutput()->GetDataTree();

    //Set the output variable properly.
    int nleaves;
    vtkDataSet **leaves = tree->GetAllLeaves(nleaves);
    for (int i = 0; i < nleaves; i++)
    {
        if (leaves[i]->GetPointData()->GetScalars())
            leaves[i]->GetPointData()->GetScalars()->SetName(pipelineVariable);
        else if (leaves[i]->GetCellData()->GetScalars())
            leaves[i]->GetCellData()->GetScalars()->SetName(pipelineVariable);
    }
    delete [] leaves;

    SetOutputDataTree(tree);
    //delete f;
}

void
avtRFilter::RegisterOperations(ScriptManager *manager)
{
    manager->RegisterOperation(&rtimeOp);
    manager->RegisterOperation(&rsimpleOp);
    manager->RegisterOperation(&revOp);
    manager->RegisterOperation(&rmiOp);
}

ScriptOperation::ScriptOperationResponse
avtRFilter::avtRExtremeValueAnalysisOperation::GetSignature(std::string& name,
                          stringVector& argnames,
                          std::vector<ScriptOperation::ScriptVariantTypeEnum>& argtypes)
{
    name = "r_extreme_value_analysis";

    argnames.push_back("aggregation");
    argtypes.push_back(ScriptOperation::INT_TYPE);

    argnames.push_back("monthtly");
    argtypes.push_back(ScriptOperation::INT_TYPE);

    argnames.push_back("seasonal");
    argtypes.push_back(ScriptOperation::INT_TYPE);

    argnames.push_back("dumpData");
    argtypes.push_back(ScriptOperation::BOOL_TYPE);

    argnames.push_back("dataScaling");
    argtypes.push_back(ScriptOperation::DOUBLE_TYPE);

    return ScriptOperation::AVT_DATA_SET;
}

bool
avtRFilter::avtRExtremeValueAnalysisOperation::func(ScriptArguments &args,
                                            avtDataset_p &result)
{


//    avtRFilter* filter = getRFilter();

//    filter->SetInput(input);
//    filter->Update(contract);

//    result = filter->GetTypedOutput();

    avtRExtremesFilter *f = new avtRExtremesFilter();
    f->aggregation = (ExtremeValueAnalysisAttributes::AggregationType)args.getArg(0).AsInt();
    f->displayMonth = (ExtremeValueAnalysisAttributes::MonthType)args.getArg(1).AsInt();
    f->displaySeason = (ExtremeValueAnalysisAttributes::SeasonType)args.getArg(2).AsInt();

    std::string vlibdir = GetVisItLibraryDirectory() + VISIT_SLASH_CHAR + "r_support";
    std::string vlibrdir  = vlibdir  + VISIT_SLASH_CHAR + "Rscripts" + VISIT_SLASH_CHAR;
    f->codeDir = vlibrdir;
    f->dumpData = args.getArg(3).AsBool();
    f->scalingVal = args.getArg(4).AsDouble();

    f->SetInput(args.GetInput());

    avtContract_p spec = args.GetContract(); //GetInput()->GetOriginatingSource()->GetGeneralContract();
    avtDataObject_p dob = f->GetOutput();

    dob->Update(spec);

    result = f->GetTypedOutput();
//    avtDataTree_p tree = f->GetTypedOutput()->GetDataTree();

//    //Set the output variable properly.
//    int nleaves;
//    vtkDataSet **leaves = tree->GetAllLeaves(nleaves);
//    for (int i = 0; i < nleaves; i++)
//    {
//        if (leaves[i]->GetPointData()->GetScalars())
//            leaves[i]->GetPointData()->GetScalars()->SetName(pipelineVariable);
//        else if (leaves[i]->GetCellData()->GetScalars())
//            leaves[i]->GetCellData()->GetScalars()->SetName(pipelineVariable);
//    }
//    delete [] leaves;


//    SetOutputDataTree(tree);

    return true;
}
