/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PyRAttributes.h>
#include <ObserverToCallback.h>
#include <stdio.h>
#include <snprintf.h>

// ****************************************************************************
// Module: PyRAttributes
//
// Purpose: 
//   RAttributes
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   omitted
//
// ****************************************************************************

//
// This struct contains the Python type information and a RAttributes.
//
struct RAttributesObject
{
    PyObject_HEAD
    RAttributes *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewRAttributes(int);

std::string
PyRAttributes_ToString(const RAttributes *atts, const char *prefix)
{
    std::string str; 
    char tmpStr[1000]; 

    //Rmap
    return str;
}

static PyObject *
RAttributes_Notify(PyObject *self, PyObject *args)
{
    RAttributesObject *obj = (RAttributesObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
RAttributes_SetRmap(PyObject *self, PyObject *args)
{
    RAttributesObject *obj = (RAttributesObject *)self;

    // NOT IMPLEMENTED!!!
    // name=Rmap, type=MapNode

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
RAttributes_GetRmap(PyObject *self, PyObject *args)
{
    RAttributesObject *obj = (RAttributesObject *)self;
    // NOT IMPLEMENTED!!!
    // name=Rmap, type=MapNode
    PyObject *retval = NULL;
    return retval;
}



PyMethodDef PyRAttributes_methods[RATTRIBUTES_NMETH] = {
    {"Notify", RAttributes_Notify, METH_VARARGS},
    {"SetRmap", RAttributes_SetRmap, METH_VARARGS},
    {"GetRmap", RAttributes_GetRmap, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
RAttributes_dealloc(PyObject *v)
{
   RAttributesObject *obj = (RAttributesObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static int
RAttributes_compare(PyObject *v, PyObject *w)
{
    RAttributes *a = ((RAttributesObject *)v)->data;
    RAttributes *b = ((RAttributesObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

PyObject *
PyRAttributes_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "Rmap") == 0)
        return RAttributes_GetRmap(self, NULL);

    return Py_FindMethod(PyRAttributes_methods, self, name);
}

int
PyRAttributes_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    PyObject *obj = NULL;


    if(obj != NULL)
        Py_DECREF(obj);

    Py_DECREF(tuple);
    if( obj == NULL)
        PyErr_Format(PyExc_RuntimeError, "Unable to set unknown attribute: '%s'", name);
    return (obj != NULL) ? 0 : -1;
}

static int
RAttributes_print(PyObject *v, FILE *fp, int flags)
{
    RAttributesObject *obj = (RAttributesObject *)v;
    fprintf(fp, "%s", PyRAttributes_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
RAttributes_str(PyObject *v)
{
    RAttributesObject *obj = (RAttributesObject *)v;
    return PyString_FromString(PyRAttributes_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
#if PY_MAJOR_VERSION > 2 || (PY_MAJOR_VERSION == 2 && PY_MINOR_VERSION >= 5)
static const char *RAttributes_Purpose = "RAttributes";
#else
static char *RAttributes_Purpose = "RAttributes";
#endif

//
// The type description structure
//
static PyTypeObject RAttributesType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "RAttributes",                    // tp_name
    sizeof(RAttributesObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)RAttributes_dealloc,  // tp_dealloc
    (printfunc)RAttributes_print,     // tp_print
    (getattrfunc)PyRAttributes_getattr, // tp_getattr
    (setattrfunc)PyRAttributes_setattr, // tp_setattr
    (cmpfunc)RAttributes_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)RAttributes_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    RAttributes_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static RAttributes *defaultAtts = 0;
static RAttributes *currentAtts = 0;

static PyObject *
NewRAttributes(int useCurrent)
{
    RAttributesObject *newObject;
    newObject = PyObject_NEW(RAttributesObject, &RAttributesType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new RAttributes(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new RAttributes(*defaultAtts);
    else
        newObject->data = new RAttributes;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapRAttributes(const RAttributes *attr)
{
    RAttributesObject *newObject;
    newObject = PyObject_NEW(RAttributesObject, &RAttributesType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (RAttributes *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
RAttributes_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewRAttributes(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef RAttributesMethods[] = {
    {"RAttributes", RAttributes_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *RAttributesObserver = 0;

std::string
PyRAttributes_GetLogString()
{
    std::string s("RAtts = RAttributes()\n");
    if(currentAtts != 0)
        s += PyRAttributes_ToString(currentAtts, "RAtts.");
    return s;
}

static void
PyRAttributes_CallLogRoutine(Subject *subj, void *data)
{
    RAttributes *atts = (RAttributes *)subj;
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("RAtts = RAttributes()\n");
        s += PyRAttributes_ToString(currentAtts, "RAtts.");
        cb(s);
    }
}

void
PyRAttributes_StartUp(RAttributes *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyRAttributes_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(RAttributesObserver == 0)
    {
        RAttributesObserver = new ObserverToCallback(subj,
            PyRAttributes_CallLogRoutine, (void *)data);
    }

}

void
PyRAttributes_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete RAttributesObserver;
    RAttributesObserver = 0;
}

PyMethodDef *
PyRAttributes_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return RAttributesMethods;
}

bool
PyRAttributes_Check(PyObject *obj)
{
    return (obj->ob_type == &RAttributesType);
}

RAttributes *
PyRAttributes_FromPyObject(PyObject *obj)
{
    RAttributesObject *obj2 = (RAttributesObject *)obj;
    return obj2->data;
}

PyObject *
PyRAttributes_New()
{
    return NewRAttributes(0);
}

PyObject *
PyRAttributes_Wrap(const RAttributes *attr)
{
    return WrapRAttributes(attr);
}

void
PyRAttributes_SetParent(PyObject *obj, PyObject *parent)
{
    RAttributesObject *obj2 = (RAttributesObject *)obj;
    obj2->parent = parent;
}

void
PyRAttributes_SetDefaults(const RAttributes *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new RAttributes(*atts);
}

