/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <RAttributes.h>
#include <DataNode.h>

// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Init utility for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void RAttributes::Init()
{

    RAttributes::SelectAll();
}

// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Copy utility for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void RAttributes::Copy(const RAttributes &obj)
{
    Rmap = obj.Rmap;

    RAttributes::SelectAll();
}

// Type map format string
const char *RAttributes::TypeMapFormatString = RATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t RAttributes::TmfsStruct = {RATTRIBUTES_TMFS};


// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Default constructor for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes::RAttributes() : 
    AttributeSubject(RAttributes::TypeMapFormatString)
{
    RAttributes::Init();
}

// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Constructor for the derived classes of RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes::RAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    RAttributes::Init();
}

// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Copy constructor for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes::RAttributes(const RAttributes &obj) : 
    AttributeSubject(RAttributes::TypeMapFormatString)
{
    RAttributes::Copy(obj);
}

// ****************************************************************************
// Method: RAttributes::RAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes::RAttributes(const RAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    RAttributes::Copy(obj);
}

// ****************************************************************************
// Method: RAttributes::~RAttributes
//
// Purpose: 
//   Destructor for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes::~RAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: RAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

RAttributes& 
RAttributes::operator = (const RAttributes &obj)
{
    if (this == &obj) return *this;

    RAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: RAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
RAttributes::operator == (const RAttributes &obj) const
{
    // Create the return value
    return ((Rmap == obj.Rmap));
}

// ****************************************************************************
// Method: RAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
RAttributes::operator != (const RAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: RAttributes::TypeName
//
// Purpose: 
//   Type name method for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
RAttributes::TypeName() const
{
    return "RAttributes";
}

// ****************************************************************************
// Method: RAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
RAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const RAttributes *tmp = (const RAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: RAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
RAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new RAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: RAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the RAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
RAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new RAttributes(*this);
    else
        retval = new RAttributes;

    return retval;
}

// ****************************************************************************
// Method: RAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
RAttributes::SelectAll()
{
    Select(ID_Rmap, (void *)&Rmap);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: RAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
RAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    RAttributes defaultObject;
    bool addToParent = false;
    // Create a node for RAttributes.
    DataNode *node = new DataNode("RAttributes");

    if(completeSave || !FieldsEqual(ID_Rmap, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("Rmap", Rmap));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: RAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
RAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("RAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("Rmap")) != 0)
        SetRmap(node->AsMapNode());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
RAttributes::SetRmap(const MapNode &Rmap_)
{
    Rmap = Rmap_;
    Select(ID_Rmap, (void *)&Rmap);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

const MapNode &
RAttributes::GetRmap() const
{
    return Rmap;
}

MapNode &
RAttributes::GetRmap()
{
    return Rmap;
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
RAttributes::SelectRmap()
{
    Select(ID_Rmap, (void *)&Rmap);
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: RAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
RAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_Rmap: return "Rmap";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: RAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
RAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_Rmap: return FieldType_MapNode;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: RAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
RAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_Rmap: return "MapNode";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: RAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
RAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const RAttributes &obj = *((const RAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_Rmap:
        {  // new scope
        retval = (Rmap == obj.Rmap);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

