/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtALSFileFormat.C                           //
// ************************************************************************* //

#include <avtALSFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>

#include <hdf5.h>
#include <avtParallel.h>

using     std::string;


// ****************************************************************************
//  Method: avtALSFileFormat constructor
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

avtALSFileFormat::avtALSFileFormat(const char *filename)
    : avtSTMDFileFormat(&filename, 1)
{
    m_filename = filename;
    m_dim1 = m_dim2 = m_nslices = 0;

    Initialize();
}


void
avtALSFileFormat::Initialize() {
    hid_t           file;           /* Handle */
    herr_t          status;

    (void) status; /// remove warning..

    file = H5Fopen (m_filename.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);

    /// main group seems to be based on filename..
    std::string group_name = m_filename;
    size_t index = m_filename.rfind("/");

    if(index != std::string::npos)
        group_name = m_filename.substr(index+1);

    group_name = group_name.substr(0, group_name.size()-std::string(".h5").length());

    hid_t group_id = H5Gopen1(file, group_name.c_str());

    hsize_t num_objs = 0;
    H5Gget_num_objs(group_id, &num_objs);
    /// get nslices attributes to read in the number of slices.

    int dim1, dim2, dim3;
    /// read only the first one, perform a sanity check against all
    /// if really necessary.

    for(size_t i = 0; i < 1; /*num_objs*/ ++i)
    {
        char name[1024];
        H5Gget_objname_by_idx(group_id, i, name, 1024);

        hid_t attr_id;

        hid_t dataset_id = H5Dopen1(group_id, name);

        attr_id = H5Aopen(dataset_id, "dim1", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim1);
        H5Aclose(attr_id);

        attr_id = H5Aopen(dataset_id, "dim2", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim2);
        H5Aclose(attr_id);

        attr_id = H5Aopen(dataset_id, "dim3", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim3);
        H5Aclose(attr_id);

        H5Dclose(dataset_id);

        //std::cout << name << std::endl;
        //std::cout << dim1 << " " << dim2 << " " << dim3 << std::endl;
    }

    ///shift by 1 dimension to make last dimension total number of slices..
    m_dim1 = dim2;
    m_dim2 = dim3;
    m_nslices = num_objs;

    H5Gclose(group_id);
    status = H5Fclose(file);
}

vtkDataArray*
avtALSFileFormat::GetDataSet() {

    hid_t           file;           /* Handle */
    herr_t          status;

    (void) status; /// remove warning..

    vtkFloatArray* array = vtkFloatArray::New();
    array->SetNumberOfTuples(m_dim1 * m_dim2 * m_nslices);

    file = H5Fopen (m_filename.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);

    /// main group seems to be based on filename..
    std::string group_name = m_filename;
    size_t index = m_filename.rfind("/");

    if(index != std::string::npos)
        group_name = m_filename.substr(index+1);

    group_name = group_name.substr(0, group_name.size()-std::string(".h5").length());

    hid_t group_id = H5Gopen1(file, group_name.c_str());

    hsize_t num_objs = 0;
    H5Gget_num_objs(group_id, &num_objs);
    /// get nslices attributes to read in the number of slices.

    int dim1, dim2, dim3;

    /// read only the first one, perform a sanity check against all
    /// if really necessary.

    for(size_t i = 0; i < num_objs; ++i)
    {
        char name[1024];
        H5Gget_objname_by_idx(group_id, i, name, 1024);

        hid_t attr_id;

        hid_t dataset_id = H5Dopen1(group_id, name);

        attr_id = H5Aopen(dataset_id, "dim1", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim1);
        H5Aclose(attr_id);

        attr_id = H5Aopen(dataset_id, "dim2", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim2);
        H5Aclose(attr_id);

        attr_id = H5Aopen(dataset_id, "dim3", H5P_DEFAULT);
        H5Aread(attr_id, H5T_NATIVE_INT, &dim3);
        H5Aclose(attr_id);

        ///dim1 should be 1, dim2 and dim3 is the size of the dataset
        H5Dread(dataset_id, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT,array->GetVoidPointer(i*dim2*dim3));
        H5Dclose(dataset_id);

        //std::cout << name << std::endl;
        //std::cout << dim1 << " " << dim2 << " " << dim3 << std::endl;
    }

    H5Gclose(group_id);
    status = H5Fclose(file);

    return array;
}

// ****************************************************************************
//  Method: avtALSFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

void
avtALSFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtALSFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

void
avtALSFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
    std::string meshname = "mesh";

    avtMeshType mt = AVT_RECTILINEAR_MESH;

    int dimensions = 3;
    int nblocks = 1; //possibly change this for parallel implementation?
    int block_origin = 0;
    int spatial_dimension = dimensions;
    int topological_dimension = dimensions;
    const double *extents = NULL;

    //const int *bounds = NULL;
    AddMeshToMetaData(md, meshname, mt, extents, nblocks, block_origin,
                      spatial_dimension, topological_dimension);


    //Add Scalar information
    std::string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    std::string varname = "intensity";
    avtCentering cent = AVT_NODECENT;
    //    std::cout << "adding variable: " << varname << std::endl;
    AddScalarVarToMetaData(md, varname, mesh_for_this_var, cent);

    //telling the meta data that we can do dynamic domain decomposition
    md->SetFormatCanDoDomainDecomposition(true);
}


// ****************************************************************************
//  Method: avtALSFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      domain      The index of the domain.  If there are NDomains, this
//                  value is guaranteed to be between 0 and NDomains-1,
//                  regardless of block origin.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

vtkDataSet *
avtALSFileFormat::GetMesh(int domain, const char *meshname)
{
    vtkRectilinearGrid* dataset = vtkRectilinearGrid::New();

    vtkFloatArray* xArray = vtkFloatArray::New();
    xArray->SetNumberOfTuples(m_dim1);
    xArray->SetNumberOfComponents(1);
    for(size_t i = 0; i < m_dim1; ++i)
        xArray->SetTuple1(i, i);

    vtkFloatArray* yArray = vtkFloatArray::New();
    yArray->SetNumberOfTuples(m_dim2);
    yArray->SetNumberOfComponents(1);
    for(size_t i = 0; i < m_dim2; ++i)
        yArray->SetTuple1(i, i);

    vtkFloatArray* zArray = vtkFloatArray::New();
    zArray->SetNumberOfTuples(m_nslices);
    zArray->SetNumberOfComponents(1);
    for(size_t i = 0; i < m_nslices; ++i)
        zArray->SetTuple1(i, i);

    dataset->SetXCoordinates(xArray);
    dataset->SetYCoordinates(yArray);
    dataset->SetZCoordinates(zArray);

    dataset->SetDimensions(m_dim1, m_dim2, m_nslices);

    xArray->Delete();
    yArray->Delete();
    zArray->Delete();

    return dataset;
}


// ****************************************************************************
//  Method: avtALSFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

vtkDataArray *
avtALSFileFormat::GetVar(int domain, const char *varname)
{
     return GetDataSet();
}


// ****************************************************************************
//  Method: avtALSFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Mon Apr 14 16:36:42 PST 2014
//
// ****************************************************************************

vtkDataArray *
avtALSFileFormat::GetVectorVar(int domain, const char *varname)
{
    return NULL;
}
