/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtScriptFilter.C
// ************************************************************************* //

#include <avtScriptFilter.h>
#include <avtPythonFilterEnvironment.h>
#include <Python.h>
#include <vtkDataSet.h>

// ****************************************************************************
//  Method: avtScriptFilter constructor
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
// ****************************************************************************

avtScriptFilter::avtScriptFilter()
:pyEnv(NULL)
{
    pyEnv = new avtPythonFilterEnvironment();

    std::cout << "executing.." << std::endl;
    if(!pyEnv->Initialize())
        std::cout << "Failed to initialize python environment.." << std::endl;

    std::string script = "";
    script += "import sys\n";
    script  = "import os\n";
    script += "import json\n";
    script += "from flow import *\n";
    script += "from flow.filters import spipeline\n";

    /// initialize environment
    if(!pyEnv->Interpreter()->RunScript(script))
        std::cout << "Script Failed.." << std::endl;
}


// ****************************************************************************
//  Method: avtScriptFilter destructor
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
//  Modifications:
//
// ****************************************************************************

avtScriptFilter::~avtScriptFilter()
{
    if(pyEnv)
        delete pyEnv;
}


// ****************************************************************************
//  Method:  avtScriptFilter::Create
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
// ****************************************************************************

avtFilter *
avtScriptFilter::Create()
{
    return new avtScriptFilter();
}


// ****************************************************************************
//  Method:      avtScriptFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
// ****************************************************************************

void
avtScriptFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const ScriptAttributes*)a;
}


// ****************************************************************************
//  Method: avtScriptFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtScriptFilter with the given
//      parameters would result in an equivalent avtScriptFilter.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
// ****************************************************************************

bool
avtScriptFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(ScriptAttributes*)a);
}


// ****************************************************************************
//  Method: avtScriptFilter::ExecuteData
//
//  Purpose:
//      Sends the specified input and output through the Script filter.
//
//  Arguments:
//      in_ds      The input dataset.
//      <unused>   The domain number.
//      <unused>   The label.
//
//  Returns:       The output dataset.
//
//  Programmer: hari -- generated by xml2avt
//  Creation:   Wed Jan 16 18:16:39 PST 2013
//
// ****************************************************************************
vtkDataSet *
avtScriptFilter::ExecuteData(vtkDataSet *in_ds, int, std::string)
{
    std::string script = "";
    /// Setup input dataset to python registry..
    MapNode node = atts.GetScriptMap();
    //std::cout << node.ToXML() << std::endl;
    std::string json_string = node["filter"].AsString();
    std::cout << json_string << std::endl;
    // create python string
    PyObject *py_json_str = PyString_FromString(json_string.c_str());
    pyEnv->Interpreter()->SetGlobalObject(py_json_str,"sdef_json");
    script   = "sdef = json.loads(sdef_json)\n";
    script  += "print json.dumps(sdef,indent=2)\n";
    /// initialize environment
    if(!pyEnv->Interpreter()->RunScript(script))
    {
        std::cout << "Script Failed.." << std::endl;
        std::cout << pyEnv->Interpreter()->ErrorMessage() << std::endl;
    }
    // create a workspace
    script  = "w = Workspace()\n";
    // register the scripts
    script += "spipeline.register_user_scripts(sdef['scripts'])\n";
    script += "w.register_filters(spipeline)\n";
    // put the input mesh into the registry
    PyObject* py_ds_in = pyEnv->WrapVTKObject(in_ds,"vtkDataSet");
    pyEnv->Interpreter()->SetGlobalObject(py_ds_in,"ds_in");
    script += "w.register_filters(spipeline)\n";
    // load the data flow
    script += "w.load_dict(sdef)\n";
    script += "w.registry_add(':src_a',2)\n";
    script += "w.registry_add(':src_b',3)\n";
    // get the visit vars
    script += "res = ds_in\n";
    script += "print w.execute()\n";
    script += "print (2+3)*(2+3) + (3-2)*(3-2)\n";    
    if(!pyEnv->Interpreter()->RunScript(script))
    {
        std::cout << "Script Failed.." << std::endl;
        std::cout << pyEnv->Interpreter()->ErrorMessage() << std::endl;
    }
    PyObject *py_res = pyEnv->Interpreter()->GetGlobalObject("res");
    if(py_ds_in == NULL)
        std::cout << "BAD ERROR" <<std::endl;
    vtkDataSet *res = (vtkDataSet*)pyEnv->UnwrapVTKObject(py_res,"vtkDataSet");
    res->Register(NULL);
    return in_ds;

}


