
SET(BUILTIN_FUNCTIONS_LIBG_SOURCES
BuiltInFunctions/QvisScriptBuiltInFunctionsWidget.C
)

SET(BUILTIN_FUNCTIONS_LIBG_MOC_SOURCES
BuiltInFunctions/QvisScriptBuiltInFunctionsWidget.h
)

LIST(APPEND LIBG_SOURCES ${BUILTIN_FUNCTIONS_LIBG_SOURCES})
LIST(APPEND LIBG_MOC_SOURCES ${BUILTIN_FUNCTIONS_LIBG_MOC_SOURCES})


INCLUDE_DIRECTORIES(BuiltInFunctions)
