
SET(CONSTANT_LIBG_SOURCES
Constant/QvisScriptConstantWidget.C
)

SET(CONSTANT_LIBG_MOC_SOURCES
Constant/QvisScriptConstantWidget.h
)

LIST(APPEND LIBG_SOURCES ${CONSTANT_LIBG_SOURCES})
LIST(APPEND LIBG_MOC_SOURCES ${CONSTANT_LIBG_MOC_SOURCES})

INCLUDE_DIRECTORIES(Constant)

