
SET(R_LIBG_SOURCES
R/QvisScriptRWidget.C
R/QvisRSyntaxHighlighter.C
)

SET(R_LIBG_MOC_SOURCES
R/QvisScriptRWidget.h
R/QvisRSyntaxHighlighter.h
)

LIST(APPEND LIBG_SOURCES ${R_LIBG_SOURCES})
LIST(APPEND LIBG_MOC_SOURCES ${R_LIBG_MOC_SOURCES})


INCLUDE_DIRECTORIES(R)
