/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <ScriptAttributes.h>
#include <DataNode.h>
#include <JSONNode.h>

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Init utility for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScriptAttributes::Init()
{
    ScriptAttributes::SelectAll();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy utility for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScriptAttributes::Copy(const ScriptAttributes &obj)
{
    ScriptMap = obj.ScriptMap;

    ScriptAttributes::SelectAll();
}

// Type map format string
const char *ScriptAttributes::TypeMapFormatString = SCRIPTATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t ScriptAttributes::TmfsStruct = {SCRIPTATTRIBUTES_TMFS};


// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Default constructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes() : 
    AttributeSubject(ScriptAttributes::TypeMapFormatString)
{
    ScriptAttributes::Init();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Constructor for the derived classes of ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScriptAttributes::Init();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy constructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(const ScriptAttributes &obj) : 
    AttributeSubject(ScriptAttributes::TypeMapFormatString)
{
    ScriptAttributes::Copy(obj);
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(const ScriptAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScriptAttributes::Copy(obj);
}

// ****************************************************************************
// Method: ScriptAttributes::~ScriptAttributes
//
// Purpose: 
//   Destructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::~ScriptAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: ScriptAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes& 
ScriptAttributes::operator = (const ScriptAttributes &obj)
{
    if (this == &obj) return *this;

    ScriptAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: ScriptAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::operator == (const ScriptAttributes &obj) const
{
    // Create the return value
    return ((ScriptMap == obj.ScriptMap));
}

// ****************************************************************************
// Method: ScriptAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::operator != (const ScriptAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: ScriptAttributes::TypeName
//
// Purpose: 
//   Type name method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
ScriptAttributes::TypeName() const
{
    return "ScriptAttributes";
}

// ****************************************************************************
// Method: ScriptAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const ScriptAttributes *tmp = (const ScriptAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: ScriptAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScriptAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new ScriptAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: ScriptAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScriptAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new ScriptAttributes(*this);
    else
        retval = new ScriptAttributes;

    return retval;
}

// ****************************************************************************
// Method: ScriptAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScriptAttributes::SelectAll()
{
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScriptAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    ScriptAttributes defaultObject;
    bool addToParent = false;
    // Create a node for ScriptAttributes.
    DataNode *node = new DataNode("ScriptAttributes");

    if(completeSave || !FieldsEqual(ID_ScriptMap, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("ScriptMap", ScriptMap));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: ScriptAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScriptAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("ScriptAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("ScriptMap")) != 0)
        SetScriptMap(node->AsMapNode());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
ScriptAttributes::SetScriptMap(const MapNode &ScriptMap_)
{
    ScriptMap = ScriptMap_;
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

const MapNode &
ScriptAttributes::GetScriptMap() const
{
    return ScriptMap;
}

MapNode &
ScriptAttributes::GetScriptMap()
{
    return ScriptMap;
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
ScriptAttributes::SelectScriptMap()
{
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScriptAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScriptAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return "ScriptMap";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScriptAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
ScriptAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return FieldType_MapNode;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: ScriptAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScriptAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return "MapNode";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScriptAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const ScriptAttributes &obj = *((const ScriptAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_ScriptMap:
        {  // new scope
        retval = (ScriptMap == obj.ScriptMap);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

void replace(std::string& str, const std::string& oldStr, const std::string& newStr)
{
  size_t pos = 0;
  while((pos = str.find(oldStr, pos)) != std::string::npos)
  {
     str.replace(pos, oldStr.length(), newStr);
     pos += newStr.length();
  }
}


void
ScriptAttributes::AddConstant(const std::string& name, const std::string& constant)
{
    JSONNode node;

    JSONNode vars = JSONNode::JSONArray();
    node["vars"] = vars;

    char buf[1024];
    sprintf(buf,"setout(%s)",constant.c_str());
    node["source"] = buf;

    /// register constant also as a node..
    JSONNode cnode;
    cnode["type"] = name;

    script["nodes"][name] = cnode;
    script["scripts"][name] = node;

    //update scriptmap
    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void
ScriptAttributes::AddFunction(const std::string& name, const stringVector& atts)
{
    JSONNode vars = JSONNode::JSONArray();
    for(int i = 0; i < atts.size(); ++i)
        vars.Append(atts[i]);

    JSONNode node;
    node["vars"] = vars;

    std::string argstring = "";
    for(size_t i = 0; i < atts.size(); ++i)
        argstring += atts[i] + (i == atts.size()-1 ? "" : ",");

   // char buf[1024];
   // sprintf(buf,"import visit_internal_funcs\nsetout(visit_internal_funcs.%s(%s))",name.c_str(),argstring.c_str());

    std::ostringstream ostr;

    ostr << "import visit_internal_funcs\n"
         << "print dir(visit_internal_funcs)\n"
         << "setout(visit_internal_funcs." << name << "(" << argstring << "))" << std::endl;

    std::string escapedCode = ostr.str();
    std::cout << escapedCode << std::endl;
    replace(escapedCode, "\n", "\\n");

    node["source"] = escapedCode;

    script["scripts"][name] = node;

    //update scriptmap
    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}


void
ScriptAttributes::AddNode(const std::string& name, const std::string& type)
{
    JSONNode node;
    node["type"] = type;
    script["nodes"][name] = node;

    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void
ScriptAttributes::AddConnection(const std::string& from, const std::string& to, const std::string& portName)
{
    JSONNode conn;
    conn["from"] = from;
    conn["to"] = to;
    conn["port"] = portName;

    if(!script.HasKey("connections"))
        script["connections"] = JSONNode::JSONArray();

    script["connections"].Append(conn);

    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void
ScriptAttributes::AddFinalOutputConnection(const std::string &from)
{
    JSONNode node;
    node["type"] = "<sink>";
    script["nodes"]["sink"] = node;

    JSONNode conn;
    conn["from"] = from;
    conn["to"] = "sink";
    conn["port"] = "in";

    if(!script.HasKey("connections"))
        script["connections"] = JSONNode::JSONArray();

    script["connections"].Append(conn);

    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void
ScriptAttributes::AddRScript(const std::string& name, const stringVector& atts, const std::string& code)
{
    JSONNode vars = JSONNode::JSONArray();
    for(int i = 0; i < atts.size(); ++i)
        vars.Append(atts[i]);

    JSONNode node;
    node["vars"] = vars;

    std::string argstring = "";
    for(size_t i = 0; i < atts.size(); ++i)
        argstring += atts[i] + (i == atts.size()-1 ? "" : ",");

    std::ostringstream rwrapper;

    rwrapper << "import rpy2,numpy\n"
             << "import rpy2.robjects as robjects\n"
             << "import rpy2.robjects.numpy2ri\n"
             << "rpy2.robjects.numpy2ri.activate()\n"
             << "_r_output = None\n"
             << "def _r_setout(out):\n"
             << "  global _r_output\n"
             << "  _r_output = out\n"
             << "r_setout = rpy2.rinterface.rternalize(_r_setout)\n"
             << "rpy2.robjects.globalenv['setout'] = r_setout\n"
             << "r_f = robjects.r('''\n"
             << "(function(" + argstring + ") { \n"
             << code
             << "})\n"
             << "''')\n"
             << "r=r_f("+ argstring + ")\n"
             << "setout(numpy.asarray(_r_output))\n";

    std::string escapedCode = rwrapper.str();
    replace(escapedCode, "\n", "\\n");

    node["source"] = escapedCode;

    script["scripts"][name] = node;

    //update scriptmap
    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void ScriptAttributes::AddPythonScript(const std::string& name, const stringVector& atts, const std::string& code)
{
    JSONNode vars = JSONNode::JSONArray();
    for(int i = 0; i < atts.size(); ++i)
        vars.Append(atts[i]);

    JSONNode node;
    node["vars"] = vars;

    std::ostringstream pwrapper;

    pwrapper << "from visit_internal_funcs import *\n"
             << code
             << "\n";
    std::string escapedCode = pwrapper.str();
    replace(escapedCode, "\n", "\\n");

    node["source"] = escapedCode;

    script["scripts"][name] = node;

    //update scriptmap
    ScriptMap["filter"] = script.ToString();
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

void
ScriptAttributes::LoadRKernel(const std::string& name, const JSONNode &atts, const std::string& code)
{
//    script = JSONNode();
//    ScriptMap = MapNode();

//    AddRScript(name,atts,code);
//    AddFinalOutputConnection(name);
}

/// convert json object to set up pipeline..

bool
ScriptAttributes::SetupPipeline(const JSONNode& atts, stringVector& args, const std::string& parent)
{
    if(atts.GetType() != JSONNode::JSONARRAY)
        return false;

    const JSONNode::JSONArray& array = atts.GetArray();

    for(int i = 0; i < array.size(); ++i)
    {
        /// need key, value pair
        /// this can be in the form of a dictionary, "a = b", pair tuple (a,b), or a pair array [a,b]
        JSONNode node = array[i];
        JSONNode key,value;
        if(node.GetType() == JSONNode::JSONARRAY)
        {
            if(node.GetArray().size() != 2) continue;

            key = node.GetArray()[0];
            value = node.GetArray()[1];
        }
        else if(node.GetType() == JSONNode::JSONOBJECT)
        {
            /// parse through dictionary and compute arguments from names..
            const JSONNode::JSONObject& obj = node.GetJsonObject();
            if(obj.size() != 1) continue;

            const JSONNode::JSONObject::const_iterator itr = obj.begin();
            key = itr->first;
            value = itr->second;
        }
        else if(node.GetType() == JSONNode::JSONSTRING)
        {
            std::string pair = node.GetString();
            int index = pair.find("=");
            if(index == std::string::npos) continue;
            key = pair.substr(0,index);
            value = pair.substr(index+1);
         }

        if(key.GetType() != JSONNode::JSONSTRING) continue;

        std::string keystr = key.GetString();

        std::ostringstream str;
        str << "import json\n"
            << "setout(json.loads(\"" << value.ToString()
            << "\"))\n";

        //std::cout << "output = " << keystr << " " << str.str() << std::endl;
        AddPythonScript(keystr,stringVector(),str.str());
        AddNode(keystr,keystr);
        AddConnection(keystr,parent,keystr);
        args.push_back(keystr);
    }
    return true;
}

void
ScriptAttributes::LoadPythonKernel(const std::string& name, const JSONNode& atts, const std::string& code)
{
    script = JSONNode();
    ScriptMap = MapNode();

    stringVector args;
    SetupPipeline(atts,args,name);

    for(int i = 0; i < args.size(); ++i)
        std::cout << args[i] << std::endl;

    AddPythonScript(name,args,code);
    AddNode(name,name);
    AddFinalOutputConnection(name);
}
