/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <ScriptAttributes.h>
#include <DataNode.h>
#include <JSONNode.h>
// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Init utility for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScriptAttributes::Init()
{
    JSONNode master;

     JSONNode scripts, nodes, conns;

     JSONNode addScript, subScript, multScript;
     JSONNode vars = JSONNode::JSONArray();

     vars.GetArray().push_back("a");
     vars.GetArray().push_back("b");


 //    sdef["scripts"] = {"add":{"source":"r=a+b\\nsetout(r)",
 //    "vars":["a","b"]},
     addScript["source"] = "r=a+b\\nsetout(r)";
     addScript["vars"] = vars;

 //    "sub":{"source":"r=a-b\nsetout(r)",
 //        "vars":["a","b"]},
     subScript["source"] = "r=a-b\\nsetout(r)";
     subScript["vars"] = vars;
 //    "mult":{"source":"r=a*b\nsetout(r)",
 //        "vars":["a","b"]}}
     multScript["source"] = "r=a*b\\nsetout(r)";
     multScript["vars"] = vars;

     scripts["add"] = addScript;
     scripts["sub"] = subScript;
     scripts["mult"] = multScript;

     JSONNode node;
 //    sdef["nodes"] = {"f1":{"type":"add"},
     node["type"] = "add"; nodes["f1"] = node;
 //    "f2":{"type":"sub"},
     node["type"] = "sub"; nodes["f2"] = node;
 //    "f3":{"type":"mult"},
     node["type"] = "mult"; nodes["f3"] = node;
 //    "f4":{"type":"mult"},
     node["type"] = "mult"; nodes["f4"] = node;
 //    "f5":{"type":"add"}}
     node["type"] = "add"; nodes["f5"] = node;

     conns = JSONNode::JSONArray();

     JSONNode conn;

 //    sdef["connections"] = [{"from":":src_a","to":"f1","port":"a"},
     conn["from"] = ":src_a"; conn["to"] = "f1"; conn["port"] = "a";
     conns.GetArray().push_back(conn);

 //    {"from":":src_b","to":"f1","port":"b"},
     conn["from"] = ":src_b"; conn["to"] = "f1"; conn["port"] = "b";
     conns.GetArray().push_back(conn);

 //    {"from":":src_b","to":"f2","port":"a"},
     conn["from"] = ":src_b"; conn["to"] = "f2"; conn["port"] = "a";
     conns.GetArray().push_back(conn);

 //    {"from":":src_a","to":"f2","port":"b"},
     conn["from"] = ":src_a"; conn["to"] = "f2"; conn["port"] = "b";
     conns.GetArray().push_back(conn);

 //    {"from":"f1","to":"f3","port":"a"},
     conn["from"] = "f1"; conn["to"] = "f3"; conn["port"] = "a";
     conns.GetArray().push_back(conn);

 //    {"from":"f1","to":"f3","port":"b"},
     conn["from"] = "f1"; conn["to"] = "f3"; conn["port"] = "b";
     conns.GetArray().push_back(conn);

 //    {"from":"f2","to":"f4","port":"a"},
     conn["from"] = "f2"; conn["to"] = "f4"; conn["port"] = "a";
     conns.GetArray().push_back(conn);

 //    {"from":"f2","to":"f4","port":"b"},
     conn["from"] = "f2"; conn["to"] = "f4"; conn["port"] = "b";
     conns.GetArray().push_back(conn);

 //    {"from":"f3","to":"f5","port":"a"},
     conn["from"] = "f3"; conn["to"] = "f5"; conn["port"] = "a";
     conns.GetArray().push_back(conn);

 //    {"from":"f4","to":"f5","port":"b"}]
     conn["from"] = "f4"; conn["to"] = "f5"; conn["port"] = "b";
     conns.GetArray().push_back(conn);

     master["scripts"] = scripts;
     master["nodes"] = nodes;
     master["connections"] = conns;

     MapNode mapnode;
     mapnode["filter"] = master.ToString();

     SetScriptMap(mapnode);

    ScriptAttributes::SelectAll();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy utility for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScriptAttributes::Copy(const ScriptAttributes &obj)
{
    ScriptMap = obj.ScriptMap;

    ScriptAttributes::SelectAll();
}

// Type map format string
const char *ScriptAttributes::TypeMapFormatString = SCRIPTATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t ScriptAttributes::TmfsStruct = {SCRIPTATTRIBUTES_TMFS};


// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Default constructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes() : 
    AttributeSubject(ScriptAttributes::TypeMapFormatString)
{
    ScriptAttributes::Init();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Constructor for the derived classes of ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScriptAttributes::Init();
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy constructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(const ScriptAttributes &obj) : 
    AttributeSubject(ScriptAttributes::TypeMapFormatString)
{
    ScriptAttributes::Copy(obj);
}

// ****************************************************************************
// Method: ScriptAttributes::ScriptAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::ScriptAttributes(const ScriptAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScriptAttributes::Copy(obj);
}

// ****************************************************************************
// Method: ScriptAttributes::~ScriptAttributes
//
// Purpose: 
//   Destructor for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes::~ScriptAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: ScriptAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScriptAttributes& 
ScriptAttributes::operator = (const ScriptAttributes &obj)
{
    if (this == &obj) return *this;

    ScriptAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: ScriptAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::operator == (const ScriptAttributes &obj) const
{
    // Create the return value
    return ((ScriptMap == obj.ScriptMap));
}

// ****************************************************************************
// Method: ScriptAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::operator != (const ScriptAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: ScriptAttributes::TypeName
//
// Purpose: 
//   Type name method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
ScriptAttributes::TypeName() const
{
    return "ScriptAttributes";
}

// ****************************************************************************
// Method: ScriptAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const ScriptAttributes *tmp = (const ScriptAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: ScriptAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScriptAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new ScriptAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: ScriptAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the ScriptAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScriptAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new ScriptAttributes(*this);
    else
        retval = new ScriptAttributes;

    return retval;
}

// ****************************************************************************
// Method: ScriptAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScriptAttributes::SelectAll()
{
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScriptAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    ScriptAttributes defaultObject;
    bool addToParent = false;
    // Create a node for ScriptAttributes.
    DataNode *node = new DataNode("ScriptAttributes");

    if(completeSave || !FieldsEqual(ID_ScriptMap, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("ScriptMap", ScriptMap));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: ScriptAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScriptAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("ScriptAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("ScriptMap")) != 0)
        SetScriptMap(node->AsMapNode());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
ScriptAttributes::SetScriptMap(const MapNode &ScriptMap_)
{
    ScriptMap = ScriptMap_;
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

const MapNode &
ScriptAttributes::GetScriptMap() const
{
    return ScriptMap;
}

MapNode &
ScriptAttributes::GetScriptMap()
{
    return ScriptMap;
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
ScriptAttributes::SelectScriptMap()
{
    Select(ID_ScriptMap, (void *)&ScriptMap);
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScriptAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScriptAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return "ScriptMap";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScriptAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
ScriptAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return FieldType_MapNode;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: ScriptAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScriptAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_ScriptMap: return "MapNode";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScriptAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScriptAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const ScriptAttributes &obj = *((const ScriptAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_ScriptMap:
        {  // new scope
        retval = (ScriptMap == obj.ScriptMap);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

