
SET(VARIABLE_LIBG_SOURCES
Variable/QvisScriptVariableWidget.C
)

SET(VARIABLE_LIBG_MOC_SOURCES
Variable/QvisScriptVariableWidget.h
)

LIST(APPEND LIBG_SOURCES ${VARIABLE_LIBG_SOURCES})
LIST(APPEND LIBG_MOC_SOURCES ${VARIABLE_LIBG_MOC_SOURCES})


INCLUDE_DIRECTORIES(Variable)
