*
* Copyright (c) 2000 - 2007, The Regents of the University of California
* Produced at the Lawrence Livermore National Laboratory
* All rights reserved.
*
* This file is part of VisIt. For details, see http://www.llnl.gov/visit/. The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or materials provided with the distribution.
*  - Neither the name of the UC/LLNL nor  the names of its contributors may be
*    used to  endorse or  promote products derived from  this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED.  IN  NO  EVENT  SHALL  THE  REGENTS  OF  THE  UNIVERSITY OF
* CALIFORNIA, THE U.S.  DEPARTMENT  OF  ENERGY OR CONTRIBUTORS BE  LIABLE  FOR
* ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,  OR CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

/*
 * Generated by whitlocb@womprat.llnl.gov on Tue Apr  9 09:55:47 PDT 2002
 * for Linux womprat.llnl.gov 2.4.14 #1 SMP Thu Nov 8 10:55:30 PST 2001 i686 unknown
 */
/* THIS FILE IS GENERATED BY `detect' -- DO NOT EDIT */
#ifndef _PDFORM_H
#define _PDFORM_H

int
 lite_int_ord_f[] = {4, 3, 2, 1}, 
 lite_int_ord_d[] = {8, 7, 6, 5, 4, 3, 2, 1};

long
 lite_int_frm_f[] = {32L,  8L, 23L,  0L,  1L,  9L,  0L, 0x7FL}, 
 lite_int_frm_d[] = {64L, 11L, 52L,  0L,  1L, 12L,  0L, 0x3FFL};

/* Internal DATA_STANDARD */
data_standard
 lite_INT_STD = {4, /* size of pointer */
            2, REVERSE_ORDER, /* size and order of short */
            4, REVERSE_ORDER, /* size and order of int */
            4, REVERSE_ORDER, /* size and order of long */
            4, lite_int_frm_f, lite_int_ord_f, /* float definition */
            8, lite_int_frm_d, lite_int_ord_d}, /* double definition */
 *lite_INT_STANDARD = &lite_INT_STD;

/* Internal DATA_ALIGNMENT */
data_alignment
 lite_INT_ALG = {1, 4, 2, 4, 4, 4, 4, 0},
 *lite_INT_ALIGNMENT = &lite_INT_ALG;

#endif /* !_PDFORM_H */
